blank_issues_enabled: false
contact_links:
  - name: FooDMe discussion Q&A
    url: https://github.com/bio-raum/FooDMe2/discussions/
    about: Please ask and answer questions here. Don't forget to tag the maintainers!
