name: helper_html_report
channels:
  - conda-forge
dependencies:
  - python=3.10
  - quarto=1.5.57
  - ipykernel=6.29.5
  - nbformat=5.10.4
  - nbclient=0.10.0
  - numpy=2.1.3
  - scipy=1.14.1
  - pandas=2.2.3
  - statsmodels=0.14.4
  - pingouin=0.5.5
  - scikit-learn=1.5.2
  - scikit-image=0.24.0
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - bokeh=3.6.0
  - plotly=5.24.1
  - itables=2.2.2