title: "FooDMe2 pipeline report"
subtitle: "Taxonomic profiling of eukaryote species from food and feed materials."
custom_logo: "pipelinelogo.png"
custom_logo_title: "bio-raum/FooDMe2"
custom_logo_url: "http://www.github.com/bio-raum/FooDMe2"
skip_versions_section: true

extra_fn_clean_exts:
    - _R1
    - _R2
    - _duplicate_metrics.txt
    - .pass

report_comment: >
    This report has been generated automatically by bio-raum/FooDMe2.
    For help interpreting the outputs, please see: https://github.com/bio-raum/FooDMe2
report_header_info:
    - Contact E-mail: "mphoeppner@gmail.com"
    - Application Type: "Taxonomic profiling from amplicons"

top_modules:
    - 'general_stats'

module_order:
    - 'fastqc'
    - 'cutadapt'
    - 'custom_content'

custom_content:
    order:
        - "custom_cluster_barplot-module"
        - "custom_assignement_barplot-module"

report_section_order:
    software_versions-module:
        order: -1000

remove_sections:
    - fastp-seq-content-gc
    - fastp-seq-content-n

