name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - "**.md"
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:
  release:
    types: # This configuration does not affect the page_build event above
      - created

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Update files
        run: |
          cat CONTRIBUTING.md > docs/about/contributing.md
          cat CHANGELOG.md > docs/about/changelog.md
          cat LICENSE > docs/about/license.md

      - name: Install Dependencies
        run: pip install mkdocs-material

      - name: Publish Docs
        run: mkdocs gh-deploy -v --force
