name: Test successful pipeline execution using test profile

# Run the workflow when:
#  - a pull request is made

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_singularity:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: install singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Run the pipeline
        env:
          NXF_SINGULARITY_CACHEDIR: ./
          NXF_SINGULARITY_HOME_MOUNT: true
        run: |
          nextflow run main.nf -profile singularity --outdir ./results --reference_base ./tests/refs --run_name test --input ./tests/data/samples.tsv --primer_set "amniotes_dobrovolny" --ground_truth ./tests/data/groundtruth.tsv --max_cpus 2 --max_memory 12.GB

  test_conda:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: install conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""
          channels: conda-forge,bioconda,defaults
          channel-priority: strict

      - name: Run the pipeline
        run: |
          nextflow run main.nf -profile conda --outdir ./results --reference_base ./tests/refs --run_name test --input ./tests/data/samples.tsv --primer_set "amniotes_dobrovolny" --ground_truth ./tests/data/groundtruth.tsv --max_cpus 2 --max_memory 12.GB
