name: Test successful pipeline execution using test profile

# Run the workflow when:
#  - a pull request is made

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_apptainer:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: Setup Apptainer
        uses: eWaterCycle/setup-apptainer@4bb22c52d4f63406c49e94c804632975787312b3 # v2.0.0
        with:
          apptainer-version: 1.3.4

      - name: Run the pipeline
        env:
          NXF_APPTAINER_CACHEDIR: ./
          NXF_APPTAINER_HOME_MOUNT: true
        run: |
          nextflow run main.nf -profile apptainer,github_test --outdir ./results --reference_base ./tests/refs --run_name test --input ./tests/data/samples.tsv --primer_set "amniotes_dobrovolny" --ground_truth ./tests/data/groundtruth.tsv 
  
  test_docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: Run the pipeline
        run: |
          nextflow run main.nf -profile docker,github_test --outdir ./results --reference_base ./tests/refs --run_name test --input ./tests/data/samples.tsv --primer_set "amniotes_dobrovolny" --ground_truth ./tests/data/groundtruth.tsv 

  test_conda:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: install conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""
          channels: conda-forge,bioconda,defaults
          channel-priority: strict

      - name: Run the pipeline
        run: |
          nextflow run main.nf -profile conda,github_test --outdir ./results --reference_base ./tests/refs --run_name test --input ./tests/data/samples.tsv --primer_set "amniotes_dobrovolny" --ground_truth ./tests/data/groundtruth.tsv 
