name: Test successful pipeline execution using test profile

# Run the workflow when:
#  - a pull request is made

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: Get the repository name and current branch set as environment variable
        run: |
          echo "REPO_LOWERCASE=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          echo "REPOTITLE_LOWERCASE=$(basename ${GITHUB_REPOSITORY,,})" >> ${GITHUB_ENV}
          echo "REPO_BRANCH=${{ github.event.inputs.testbranch || 'dev' }}" >> ${GITHUB_ENV}

      - name: install singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Run the pipeline
        env:
          NXF_SINGULARITY_CACHEDIR: ./
          NXF_SINGULARITY_HOME_MOUNT: true
        run: |
          nextflow run main.nf -profile singularty --outdir ./results --reference_base ./tests/refs --run_name test --input ./tests/data/samples.tsv --primer_set "amniotes_dobrovolny" --ground_truth ./tests/data/groundtruth.tsv

