name: Test successful pipeline execution using test profile

# Run the workflow when:
#  - a pull request is made

on:
  pull_request:
    types:
      - opened
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: Get the repository name and current branch set as environment variable
        run: |
          echo "REPO_LOWERCASE=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          echo "REPOTITLE_LOWERCASE=$(basename ${GITHUB_REPOSITORY,,})" >> ${GITHUB_ENV}
          echo "REPO_BRANCH=${{ github.event.inputs.testbranch || 'dev' }}" >> ${GITHUB_ENV}

      - name: Run the pipeline
        env:
          NXF_SINGULARITY_CACHEDIR: ./
          NXF_SINGULARITY_HOME_MOUNT: true
        run: |
          nextflow run ${{ env.REPO_LOWERCASE }} -r ${{ env.REPO_BRANCH }} -profile singularity --reference_base ./refs --skip_genbank
          nextflow run ${{ env.REPO_LOWERCASE }} -r ${{ env.REPO_BRANCH }} -profile singularity,test --outdir ./results --reference_base ./refs
